# Generated by Django 2.1.7 on 2019-03-17 19:46

import bungalow.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(choices=[('SqFt', 'Square Footage')], default='SqFt', max_length=4)),
                ('bathrooms', models.FloatField(blank=True)),
                ('bedrooms', models.FloatField(blank=True)),
                ('home_size', models.FloatField(blank=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'SingleFamily'), ('VacantResidentialLand', 'VacantResidentialLand'), ('MultiFamily2To4', 'MultiFamily2To4'), ('Duplex', 'Duplex'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Miscellaneous', 'Miscellaneous')], max_length=30)),
                ('last_sold_date', bungalow.listings.models.CustomizedDateField(blank=True, null=True)),
                ('last_sold_price', models.FloatField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('price', models.CharField(blank=True, max_length=30)),
                ('property_size', models.FloatField(blank=True)),
                ('rent_price', models.FloatField(blank=True)),
                ('rentzestimate_amount', models.FloatField(blank=True)),
                ('rentzestimate_last_updated', bungalow.listings.models.CustomizedDateField(blank=True, null=True)),
                ('tax_value', models.FloatField(blank=True)),
                ('tax_year', models.FloatField(blank=True)),
                ('year_built', models.FloatField(blank=True)),
                ('zestimate_amount', models.FloatField(blank=True)),
                ('zestimate_last_updated', bungalow.listings.models.CustomizedDateField(blank=True, null=True)),
                ('zillow_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
            ],
        ),
    ]
